chore: allow custom annotations for Job objects
curityio/idsvr-helm pull request #84
Opened 2024-04-15 14:53 UTC by slivkamiro

We use istio in our environment, and it automatically injects a sidecar to all pods. However one time jobs are [getting stuck when istio is injected](https://github.com/istio/istio/issues/6324). It is possible to opt-out from injecting it using an [annotation](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy).

2024-04-15 15:10 UTC, anestos commented on idsvr/templates/post-hook.yaml
> +    {{- if .Values.curity.jobsAnnotations }}
post-hook has its own settings options in the values file, can you instead use `postHook.annotations` instead?

2024-04-15 15:11 UTC, anestos requested changes
Conseptually approved but it requires some changes before it is merged.
1. Add the new `jobsAnnotations` to default values file and readme
2. Use `postHook.annotations` for the post-hook.yaml (and add to values file and readme)
3. Revert whitespace changes if not necessary

2024-04-17 08:41 UTC, slivkamiro commented
forgot about the readme, should be ready for review now @anestos

2024-04-17 16:04 UTC, anestos approved these changes

2024-04-25 11:20 UTC, merged